  #[Momentum] Rewards and More
    #Copyright (C) <2025>  <thepixel3261>

  #This program is free software: you can redistribute it and/or modify
    #it under the terms of the GNU Affero General Public License as published
    #by the Free Software Foundation, either version 3 of the License, or
    #(at your option) any later version.

    #This program is distributed in the hope that it will be useful,
    #but WITHOUT ANY WARRANTY; without even the implied warranty of
    #MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    #GNU Affero General Public License for more details.

    #You should have received a copy of the GNU Affero General Public License
    ##along with this program.  If not, see <https://www.gnu.org/licenses/>.

  #=== Additional Terms (under Section 7) ===

    #Public Source Availability Requirement:
    #If you modify and *run* this plugin on a publicly accessible Minecraft server,
    #you must publish the complete modified source code in a publicly accessible
    #repository (e.g. GitHub, GitLab). Merely offering the source “on request” does
    #NOT fulfill this requirement.

name: Momentum
main: de.thepixel3261.momentum.Main
version: '1.2.0-SNAPSHOT'
api-version: '1.21'
author: thepixel3261
description: Track player sessions and unlock rewards over time.
load: STARTUP

softdepend:
  - Vault
  - PlaceholderAPI

commands:
  momentum:
    description: Main command for the Momentum plugin.
    aliases: [session, sessionperks]
    permission: momentum.use

permissions:
  momentum.use:
    description: Allows using the main Momentum command.
    default: true
  momentum.reload:
    description: Allows reloading the Momentum configuration.
    default: op
  momentum.multiplier:
    description: Multiply rewards by x
    children:
      - momentum.multiplier.1_0
      - momentum.multiplier.2_0
      - momentum.multiplier.3_0
    default: false

  momentum.multiplier.1_0:
    description: Multiply rewards by 1.0
    default: true
    parent: momentum.multiplier